<?
$time1=$GLOBALS["time1"];
function finish($time1)
{
    $time = microtime();
    $time = explode(" ",$time);
    $time = $time[1] + $time[0];
    $time2 = $time;
    $total = ($time2 - $time1);

    $total = round($total, 3);

    return $total;
}

echo " <!-- generated by www.PHPFlash.w.pl -->
" . finish($time1);
?>